{% set version = "1.0.0" %}
{% set linux_compiler_version = "10.4.0" %}
{% set macos_compiler_version = "12" %}

package:
  name: elements
  version: {{ version }}

source:
  - git_url: https://github.com/lanl/ELEMENTS.git
    git_depth: 1

build:
  number: 1
  noarch: False
  script_env:
    - PLATFORM={{ target_platform }} # [linux]

requirements:
  build:
    - cmake >=3.10.0
    - {{ compiler('cxx') }}={{ linux_compiler_version }} # [linux]
    - {{ compiler('cxx') }}={{ macos_compiler_version }} # [osx]

about:
  home: https://github.com/lanl/Fierro
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary:
    LANL's software for simulating quasi-static solid mechanics.
  description:
    Fierro (LANL code number C21030) is a modern C++ code designed to simulate quasi-static 
    solid mechanics problems and transient, compressible material dynamic problems with Lagrangian methods, 
    which have meshes with constant mass elements that move with the material, 
    or with Eulerian methods, which have stationary meshes. 
  dev_url: https://github.com/lanl/Fierro

extra:
  recipe-maintainers:
    - fierromechanics
