{% set version = "1.0.0" %}
{% set compiler_version = "10.4.0" %}

package:
  name: fierro-heffte
  version: {{ version }}

source:
  git_url: https://github.com/icl-utk-edu/heffte.git
  git_depth: 1

build:
  number: 1
  noarch: False
  script_env:
    - PLATFORM={{ target_platform }}

requirements:
  build:
    - cmake >=3.17.0
    - {{ compiler('c') }} ={{ compiler_version }}
    - {{ compiler('cxx') }} ={{ compiler_version }}
    - openmpi
  host:
    - openmpi
    - fftw
  run:
    - openmpi
    - fftw

about:
  home: https://github.com/lanl/Fierro
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary:
    LANL Fierro's dependency for EVPFFT solutions
  description:
    Fierro (LANL code number C21030) is a modern C++ code designed to simulate quasi-static 
    solid mechanics problems and transient, compressible material dynamic problems with Lagrangian methods, 
    which have meshes with constant mass elements that move with the material, 
    or with Eulerian methods, which have stationary meshes. 
  dev_url: https://github.com/lanl/Fierro

extra:
  recipe-maintainers:
    - kwelsh-lanl
