{% set version = "1.0.0" %}
{% set compiler_version = "10.4.0" %}

package:
  name: fierro-evpfft
  version: {{ version }}

source:
  git_url: https://github.com/lanl/Fierro.git
  git_depth: 1

build:
  number: 1
  script_env:
    - PLATFORM={{ target_platform }}

requirements:
  build:
    - cmake >=3.17.0
    - {{ compiler('c') }} ={{ compiler_version }}
    - {{ compiler('cxx') }} ={{ compiler_version }}
    - openmpi
  host:
    - openmpi
    - fierro-heffte
    - fftw=*=mpi_openmpi_*
    - kokkos
    - hdf5=*=mpi_openmpi_*
    - elements
  run:
    - openmpi
    - fierro-heffte
    - fftw=*=mpi_openmpi_*
    - kokkos
    - hdf5=*=mpi_openmpi_*
    - elements

#TODO: Add tests

about:
  home: https://github.com/lanl/Fierro
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary:
  description:
  dev_url: https://github.com/lanl/Fierro

extra:
  recipe-maintainers:
    - kwelsh-lanl
