FROM rocm/dev-ubuntu-20.04:4.3

ENV TZ=America/New_York
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update && apt install --no-install-recommends -y \
        rocm-libs \
        cmake \
        libopenmpi-dev \
        openmpi-bin \
        openssh-client \
        libomp-dev \
        libfftw3-dev \
        libfftw3-mpi-dev \
        wget \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV OPENMPI_DIR=/opt/openmpi
RUN OPENMPI_VERSION=4.0.3 && \
    OPENMPI_VERSION_SHORT=4.0 && \
    OPENMPI_SHA1=d958454e32da2c86dd32b7d557cf9a401f0a08d3 && \
    OPENMPI_URL=https://download.open-mpi.org/release/open-mpi/v${OPENMPI_VERSION_SHORT}/openmpi-${OPENMPI_VERSION}.tar.bz2 && \
    OPENMPI_ARCHIVE=openmpi-${OPENMPI_VERSION}.tar.bz2 && \
    SCRATCH_DIR=/scratch && mkdir -p ${SCRATCH_DIR} && cd ${SCRATCH_DIR} && \
    wget --quiet ${OPENMPI_URL} --output-document=${OPENMPI_ARCHIVE} && \
    echo "${OPENMPI_SHA1} ${OPENMPI_ARCHIVE}" | sha1sum -c && \
    mkdir -p openmpi && \
    tar -xf ${OPENMPI_ARCHIVE} -C openmpi --strip-components=1 && \
    mkdir -p build && cd build && \
    ../openmpi/configure --prefix=${OPENMPI_DIR} CFLAGS=-w CC=/opt/rocm/bin/amdclang CXX=/opt/rocm/bin/amdclang++ FC=/opt/rocm/bin/amdflang && \
    make -j8 install && \
    rm -rf ${SCRATCH_DIR}
ENV PATH=${OPENMPI_DIR}/bin:$PATH
