{% set version = "14.0.0" %}
{% set compiler_version = "10.4.0" %}

package:
  name: fierro-trilinos-cuda
  version: {{ version }}

source:
  url: https://github.com/trilinos/Trilinos/archive/trilinos-release-{{ version | replace('.', '-') }}.tar.gz
  md5: 24d973894e2e334c6ac9436d8b16f7cc

build:
  number: 2

requirements:
  build:
    - cmake >=3.17.0
    - {{ compiler('c') }} ={{ compiler_version }}
    - {{ compiler('cxx') }} ={{ compiler_version }}
    - {{ compiler('fortran') }} ={{ compiler_version }}
    - cuda-toolkit
    - openmpi
  host:
    - cuda-cudart-static
    - libcusolver-dev
    - libcufft-dev
    - libcublas-dev
    - libcusparse-dev
    - _openmp_mutex
    - libblas
    - liblapack
    - openmpi
    - boost-cpp
    - libnetcdf
    - libmatio
  run:
    - libblas
  
#TODO: Add tests

about:
  home: https://trilinos.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary:
    This is a specific build of Sandia's suite of HPC solvers and enabling technologies
    that is maintained solely as a dependency for the associated fierro packages.
  description:
    Fast, compiled object-oriented algorithms and enabling
    technologies that support the solution of large-scale,
    complex multi-physics engineering and scientific problems.
  dev_url: https://github.com/trilinos/Trilinos

extra:
  recipe-maintainers:
    - kwelsh-lanl
