{% set version = "2.0.0" %}
{% set linux_compiler_version = "10.4.0" %}
{% set macos_compiler_version = "16" %}
# We need the same MPI version in build + host. 
# So we have to specify it, unfortunately
# UPDATE: Not necessary right now, perhaps in the future
#{% set mpi_version = "4.1" %}

package:
  name: fierro-fe-cpu
  version: {{ version }}

source:
  git_url: https://github.com/lanl/Fierro.git
  git_depth: 1
  git_submodules: false # don't need submodules 

build:
  number: 2
  script_env:
    - PLATFORM={{ target_platform }}

requirements:
  build:
    - cmake >=3.17.0
    - {{ compiler('c') }}={{ linux_compiler_version }} # [linux]
    - {{ compiler('c') }}={{ macos_compiler_version }} # [osx]
    - {{ compiler('cxx') }}={{ linux_compiler_version }} # [linux]
    - {{ compiler('cxx') }}={{ macos_compiler_version }} # [osx]
    - {{ compiler('fortran') }}
    - openmpi
    - elements-cpu
  host:
    - _openmp_mutex # [linux]
    - llvm-openmp   # [osx]
    - trilinos-cpu
    - elements-cpu
    - openmpi >=4.1.6,<5.0a0
  run:
    - trilinos-cpu
    - openmpi >=4.1.6,<5.0a0

about:
  home: https://github.com/lanl/Fierro
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary:
    LANL's software for simulating quasi-static solid mechanics.
  description:
    Fierro (LANL code number C21030) is a modern C++ code designed to simulate quasi-static 
    solid mechanics problems and transient, compressible material dynamic problems with Lagrangian methods, 
    which have meshes with constant mass elements that move with the material, 
    or with Eulerian methods, which have stationary meshes. 
  dev_url: https://github.com/lanl/Fierro

extra:
  recipe-maintainers:
    - fierromechanics
