package: 
  name: evpfft_gui
  version: 1

source:
  path: ../../
  # - git_url: https://github.com/lanl/Fierro.git
  #   depth: 1

build:
  number: 1
  script: cd python/EVPFFT-GUI/; python setup.py install

requirements:
  host:
    - python
    - setuptools
  run:
    - paraview=5.11.2
    - fierro-evpfft
    - fierro-voxelizer-py
    - python
    - pyside6

test:
  imports:
    - evpfft_gui
