{% set version = "1.0.0" %}
{% set linux_compiler_version = "10.4.0" %}
{% set macos_compiler_version = "12" %}

package:
  name: fierro-dev
  version: {{ version }}

build:
  number: 1
  noarch: generic
  skip: True # [not (linux and x86_64)]
  script_env:
    - PLATFORM={{ target_platform }}

requirements:
  host:
    - cmake >=3.17
    - {{ compiler('c') }}={{ linux_compiler_version }} # [linux]
    - {{ compiler('c') }}={{ macos_compiler_version }} # [osx]
    - {{ compiler('cxx') }}={{ linux_compiler_version }} # [linux]
    - {{ compiler('cxx') }}={{ macos_compiler_version }} # [osx]
    - {{ compiler('fortran') }}
    - fierro-trilinos-cpu
    - mpi
    - elements
  run:
    #- cmake >=3.17
    - {{ compiler('c') }}={{ linux_compiler_version }} # [linux]
    - {{ compiler('c') }}={{ macos_compiler_version }} # [osx]
    - {{ compiler('cxx') }}={{ linux_compiler_version }} # [linux]
    - {{ compiler('cxx') }}={{ macos_compiler_version }} # [osx]
    - {{ compiler('fortran') }}
    - fierro-trilinos-cpu
    - mpi
    - elements
  
about:
  home: https://github.com/lanl/Fierro
  license: BSD-3-Clause
  license_family: BSD
  summary:
    Metapackage for consolidating development dependencies for fierro.
  dev_url: https://github.com/lanl/Fierro

extra:
  recipe-maintainers:
    - fierromechanics
