# input file
num_dims: 3

mesh_generation_options:
    type: Box
    origin: [0, 0, 0]
    length: [10, 10, 100]
    num_elems: [10, 10, 100]

materials:
  - id: 0
    elastic_modulus: 200000000000
    poisson_ratio: 0.3
    density: 7850
    thermal_conductivity: 10
    specific_internal_energy_rate: 1.0
    initial_temperature: 293

fea_module_parameters:
  - type: Inertial
    material_id: 0
    
  - type: Elasticity
    material_id: 0
    modal_analysis: true
    smallest_modes: true
    num_modes: 10
    convergence_tolerance: 1.0e-18
    # Dirichlet conditions
    boundary_conditions:
      - surface: 
          type: z_plane
          plane_position: 0.0
        type: displacement
        value: 0.0
            
    # Loading/Neumann Conditions
    loading_conditions:
      - surface: 
          type: z_plane
          plane_position: 100.0
        type: surface_traction
        component_x: 500
        component_y: 0
        component_z: 0

