name: 'Publish Heffte CUDA'

on: 
  push:
    paths:
      #- .conda/heffte/cuda/**
      #- .github/workflows/publish-heffte-cuda.yaml
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/build-conda-package.yaml
    with:
      recipe_dir: .conda/heffte/cuda
    secrets: inherit
