name: 'Publish FIERRO GUI'

on: 
  push:
    paths:
      - .conda/fierro-gui/**
      - python/FIERRO-GUI/**
      - .github/workflows/publish-fierro-gui.yaml
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/build-conda-package.yaml
    with:
      recipe_dir: .conda/fierro-gui
    secrets: inherit
